export const initialPreferences = {
  favoriteSports: [
    "Basketball",
    "American Football",
    "Rugby",
    "Field Hockey",
    "Table Tennis",
    "Cricket",
  ],
  favoriteTeams: [
    "Thunderbolts",
    "Dragonslayers",
    "Phoenix Rising",
    "Avalanche",
    "Titans",
    "Vortex Vipers",
    "Spectral Shadows",
    "Blitzkrieg",
    "Fury United",
    "Lightning Strikes",
    "Serpents of Fire",
    "Galaxy Warriors",
    "Stormbreakers",
    "Enigma Enforcers",
    "Blaze Squadron",
    "Phantom Phantoms",
    "Celestial Chargers",
    "Rebel Renegades",
    "Inferno Ignitors",
    "Stealth Strikers",
    "Nova Knights",
    "Crimson Crushers",
    "Rapid Raptors",
    "Shadow Assassins",
  ],
};
